[package]
name = "dec_6"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day6_1"
path = "src/day6_1.rs"

[[bin]]
name = "day6_2"
path = "src/day6_2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
